(cl:defpackage optimizer-msg
  (:use )
  (:export
   "<BOOLSTAMPEDMSG>"
   "BOOLSTAMPEDMSG"
   "<COLOREDIMAGEMSG>"
   "COLOREDIMAGEMSG"
   "<FLOATARRAY>"
   "FLOATARRAY"
   "<FLOATLIST>"
   "FLOATLIST"
   "<IDEPTH>"
   "IDEPTH"
   "<NNPREPROCESS>"
   "NNPREPROCESS"
   "<NNPREPROCESSLIGHT>"
   "NNPREPROCESSLIGHT"
   "<NEWMSG>"
   "NEWMSG"
   "<THREEMAP>"
   "THREEMAP"
   "<KEYFRAMEMSG>"
   "KEYFRAMEMSG"
   "<KEYFRAMEMSGMODIFIED>"
   "KEYFRAMEMSGMODIFIED"
  ))

