// Generated by gencpp from file lsd_slam_core/ColoredImageMsg.msg
// DO NOT EDIT!


#ifndef LSD_SLAM_CORE_MESSAGE_COLOREDIMAGEMSG_H
#define LSD_SLAM_CORE_MESSAGE_COLOREDIMAGEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/PoseStamped.h>

namespace lsd_slam_core
{
template <class ContainerAllocator>
struct ColoredImageMsg_
{
  typedef ColoredImageMsg_<ContainerAllocator> Type;

  ColoredImageMsg_()
    : header()
    , coloredImage()
    , POSE()
    , LSD_map()
    , Var_map()  {
    }
  ColoredImageMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coloredImage(_alloc)
    , POSE(_alloc)
    , LSD_map(_alloc)
    , Var_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _coloredImage_type;
  _coloredImage_type coloredImage;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _POSE_type;
  _POSE_type POSE;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _LSD_map_type;
  _LSD_map_type LSD_map;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _Var_map_type;
  _Var_map_type Var_map;





  typedef boost::shared_ptr< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ColoredImageMsg_

typedef ::lsd_slam_core::ColoredImageMsg_<std::allocator<void> > ColoredImageMsg;

typedef boost::shared_ptr< ::lsd_slam_core::ColoredImageMsg > ColoredImageMsgPtr;
typedef boost::shared_ptr< ::lsd_slam_core::ColoredImageMsg const> ColoredImageMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator1> & lhs, const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.coloredImage == rhs.coloredImage &&
    lhs.POSE == rhs.POSE &&
    lhs.LSD_map == rhs.LSD_map &&
    lhs.Var_map == rhs.Var_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator1> & lhs, const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lsd_slam_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c222e02e39b32be1aab36e1c565a823";
  }

  static const char* value(const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c222e02e39b32beULL;
  static const uint64_t static_value2 = 0x1aab36e1c565a823ULL;
};

template<class ContainerAllocator>
struct DataType< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lsd_slam_core/ColoredImageMsg";
  }

  static const char* value(const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image coloredImage\n"
"geometry_msgs/PoseStamped POSE\n"
"float32[] LSD_map\n"
"float32[] Var_map\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coloredImage);
      stream.next(m.POSE);
      stream.next(m.LSD_map);
      stream.next(m.Var_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColoredImageMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lsd_slam_core::ColoredImageMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coloredImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.coloredImage);
    s << indent << "POSE: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.POSE);
    s << indent << "LSD_map[]" << std::endl;
    for (size_t i = 0; i < v.LSD_map.size(); ++i)
    {
      s << indent << "  LSD_map[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.LSD_map[i]);
    }
    s << indent << "Var_map[]" << std::endl;
    for (size_t i = 0; i < v.Var_map.size(); ++i)
    {
      s << indent << "  Var_map[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.Var_map[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSD_SLAM_CORE_MESSAGE_COLOREDIMAGEMSG_H
