// Generated by gencpp from file pcl_handler/BoolStampedMsg.msg
// DO NOT EDIT!


#ifndef PCL_HANDLER_MESSAGE_BOOLSTAMPEDMSG_H
#define PCL_HANDLER_MESSAGE_BOOLSTAMPEDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pcl_handler
{
template <class ContainerAllocator>
struct BoolStampedMsg_
{
  typedef BoolStampedMsg_<ContainerAllocator> Type;

  BoolStampedMsg_()
    : header()
    , value(false)  {
    }
  BoolStampedMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BoolStampedMsg_

typedef ::pcl_handler::BoolStampedMsg_<std::allocator<void> > BoolStampedMsg;

typedef boost::shared_ptr< ::pcl_handler::BoolStampedMsg > BoolStampedMsgPtr;
typedef boost::shared_ptr< ::pcl_handler::BoolStampedMsg const> BoolStampedMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcl_handler::BoolStampedMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pcl_handler::BoolStampedMsg_<ContainerAllocator1> & lhs, const ::pcl_handler::BoolStampedMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pcl_handler::BoolStampedMsg_<ContainerAllocator1> & lhs, const ::pcl_handler::BoolStampedMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pcl_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a502021a9e661290bab60c5754fb8cd";
  }

  static const char* value(const ::pcl_handler::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a502021a9e66129ULL;
  static const uint64_t static_value2 = 0x0bab60c5754fb8cdULL;
};

template<class ContainerAllocator>
struct DataType< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcl_handler/BoolStampedMsg";
  }

  static const char* value(const ::pcl_handler::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pcl_handler::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolStampedMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcl_handler::BoolStampedMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcl_handler::BoolStampedMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCL_HANDLER_MESSAGE_BOOLSTAMPEDMSG_H
