// Generated by gencpp from file optimizer/BoolStampedMsg.msg
// DO NOT EDIT!


#ifndef OPTIMIZER_MESSAGE_BOOLSTAMPEDMSG_H
#define OPTIMIZER_MESSAGE_BOOLSTAMPEDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace optimizer
{
template <class ContainerAllocator>
struct BoolStampedMsg_
{
  typedef BoolStampedMsg_<ContainerAllocator> Type;

  BoolStampedMsg_()
    : header()
    , bool(false)  {
    }
  BoolStampedMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bool(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _bool_type;
  _bool_type bool;





  typedef boost::shared_ptr< ::optimizer::BoolStampedMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optimizer::BoolStampedMsg_<ContainerAllocator> const> ConstPtr;

}; // struct BoolStampedMsg_

typedef ::optimizer::BoolStampedMsg_<std::allocator<void> > BoolStampedMsg;

typedef boost::shared_ptr< ::optimizer::BoolStampedMsg > BoolStampedMsgPtr;
typedef boost::shared_ptr< ::optimizer::BoolStampedMsg const> BoolStampedMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optimizer::BoolStampedMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optimizer::BoolStampedMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::optimizer::BoolStampedMsg_<ContainerAllocator1> & lhs, const ::optimizer::BoolStampedMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bool == rhs.bool;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::optimizer::BoolStampedMsg_<ContainerAllocator1> & lhs, const ::optimizer::BoolStampedMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace optimizer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optimizer::BoolStampedMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::BoolStampedMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::BoolStampedMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69889c828e9b57d09fcac5f696f08fc4";
  }

  static const char* value(const ::optimizer::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69889c828e9b57d0ULL;
  static const uint64_t static_value2 = 0x9fcac5f696f08fc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optimizer/BoolStampedMsg";
  }

  static const char* value(const ::optimizer::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool bool\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::optimizer::BoolStampedMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolStampedMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optimizer::BoolStampedMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optimizer::BoolStampedMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bool);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTIMIZER_MESSAGE_BOOLSTAMPEDMSG_H
