// Generated by gencpp from file optimizer/FloatArray.msg
// DO NOT EDIT!


#ifndef OPTIMIZER_MESSAGE_FLOATARRAY_H
#define OPTIMIZER_MESSAGE_FLOATARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace optimizer
{
template <class ContainerAllocator>
struct FloatArray_
{
  typedef FloatArray_<ContainerAllocator> Type;

  FloatArray_()
    : header()
    , vector()  {
    }
  FloatArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _vector_type;
  _vector_type vector;





  typedef boost::shared_ptr< ::optimizer::FloatArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optimizer::FloatArray_<ContainerAllocator> const> ConstPtr;

}; // struct FloatArray_

typedef ::optimizer::FloatArray_<std::allocator<void> > FloatArray;

typedef boost::shared_ptr< ::optimizer::FloatArray > FloatArrayPtr;
typedef boost::shared_ptr< ::optimizer::FloatArray const> FloatArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optimizer::FloatArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optimizer::FloatArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::optimizer::FloatArray_<ContainerAllocator1> & lhs, const ::optimizer::FloatArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vector == rhs.vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::optimizer::FloatArray_<ContainerAllocator1> & lhs, const ::optimizer::FloatArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace optimizer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::optimizer::FloatArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optimizer::FloatArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::FloatArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::FloatArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::FloatArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::FloatArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optimizer::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b324c7325e683bf02a9b14b01090ec7";
  }

  static const char* value(const ::optimizer::FloatArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b324c7325e683bfULL;
  static const uint64_t static_value2 = 0x02a9b14b01090ec7ULL;
};

template<class ContainerAllocator>
struct DataType< ::optimizer::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optimizer/FloatArray";
  }

  static const char* value(const ::optimizer::FloatArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optimizer::FloatArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Vector3[] vector\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::optimizer::FloatArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optimizer::FloatArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloatArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optimizer::FloatArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optimizer::FloatArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vector[]" << std::endl;
    for (size_t i = 0; i < v.vector.size(); ++i)
    {
      s << indent << "  vector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTIMIZER_MESSAGE_FLOATARRAY_H
