// Generated by gencpp from file optimizer/FloatList.msg
// DO NOT EDIT!


#ifndef OPTIMIZER_MESSAGE_FLOATLIST_H
#define OPTIMIZER_MESSAGE_FLOATLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/CompressedImage.h>

namespace optimizer
{
template <class ContainerAllocator>
struct FloatList_
{
  typedef FloatList_<ContainerAllocator> Type;

  FloatList_()
    : header()
    , elements()
    , RGBImage()  {
    }
  FloatList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , elements(_alloc)
    , RGBImage(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _elements_type;
  _elements_type elements;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _RGBImage_type;
  _RGBImage_type RGBImage;





  typedef boost::shared_ptr< ::optimizer::FloatList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optimizer::FloatList_<ContainerAllocator> const> ConstPtr;

}; // struct FloatList_

typedef ::optimizer::FloatList_<std::allocator<void> > FloatList;

typedef boost::shared_ptr< ::optimizer::FloatList > FloatListPtr;
typedef boost::shared_ptr< ::optimizer::FloatList const> FloatListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optimizer::FloatList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optimizer::FloatList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::optimizer::FloatList_<ContainerAllocator1> & lhs, const ::optimizer::FloatList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.elements == rhs.elements &&
    lhs.RGBImage == rhs.RGBImage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::optimizer::FloatList_<ContainerAllocator1> & lhs, const ::optimizer::FloatList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace optimizer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::optimizer::FloatList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optimizer::FloatList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::FloatList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::FloatList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::FloatList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::FloatList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optimizer::FloatList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa0ffa7ee0c8405a53af12a7ef35f8ad";
  }

  static const char* value(const ::optimizer::FloatList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa0ffa7ee0c8405aULL;
  static const uint64_t static_value2 = 0x53af12a7ef35f8adULL;
};

template<class ContainerAllocator>
struct DataType< ::optimizer::FloatList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optimizer/FloatList";
  }

  static const char* value(const ::optimizer::FloatList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optimizer::FloatList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] elements\n"
"sensor_msgs/CompressedImage RGBImage\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/CompressedImage\n"
"# This message contains a compressed image\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"\n"
"string format        # Specifies the format of the data\n"
"                     #   Acceptable values:\n"
"                     #     jpeg, png\n"
"uint8[] data         # Compressed image buffer\n"
;
  }

  static const char* value(const ::optimizer::FloatList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optimizer::FloatList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.elements);
      stream.next(m.RGBImage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloatList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optimizer::FloatList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optimizer::FloatList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "elements[]" << std::endl;
    for (size_t i = 0; i < v.elements.size(); ++i)
    {
      s << indent << "  elements[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.elements[i]);
    }
    s << indent << "RGBImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.RGBImage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTIMIZER_MESSAGE_FLOATLIST_H
