// Generated by gencpp from file optimizer/NewMsg.msg
// DO NOT EDIT!


#ifndef OPTIMIZER_MESSAGE_NEWMSG_H
#define OPTIMIZER_MESSAGE_NEWMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/Point.h>

namespace optimizer
{
template <class ContainerAllocator>
struct NewMsg_
{
  typedef NewMsg_<ContainerAllocator> Type;

  NewMsg_()
    : header()
    , coloredImage()
    , POSE()
    , LSDMap()
    , depth()
    , scale(0.0)  {
    }
  NewMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coloredImage(_alloc)
    , POSE(_alloc)
    , LSDMap(_alloc)
    , depth(_alloc)
    , scale(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _coloredImage_type;
  _coloredImage_type coloredImage;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _POSE_type;
  _POSE_type POSE;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _LSDMap_type;
  _LSDMap_type LSDMap;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _depth_type;
  _depth_type depth;

   typedef double _scale_type;
  _scale_type scale;





  typedef boost::shared_ptr< ::optimizer::NewMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::optimizer::NewMsg_<ContainerAllocator> const> ConstPtr;

}; // struct NewMsg_

typedef ::optimizer::NewMsg_<std::allocator<void> > NewMsg;

typedef boost::shared_ptr< ::optimizer::NewMsg > NewMsgPtr;
typedef boost::shared_ptr< ::optimizer::NewMsg const> NewMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::optimizer::NewMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::optimizer::NewMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::optimizer::NewMsg_<ContainerAllocator1> & lhs, const ::optimizer::NewMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.coloredImage == rhs.coloredImage &&
    lhs.POSE == rhs.POSE &&
    lhs.LSDMap == rhs.LSDMap &&
    lhs.depth == rhs.depth &&
    lhs.scale == rhs.scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::optimizer::NewMsg_<ContainerAllocator1> & lhs, const ::optimizer::NewMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace optimizer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::optimizer::NewMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::optimizer::NewMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::NewMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::optimizer::NewMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::NewMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::optimizer::NewMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::optimizer::NewMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "078bbc35fe46c3fd961f9820ad417d34";
  }

  static const char* value(const ::optimizer::NewMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x078bbc35fe46c3fdULL;
  static const uint64_t static_value2 = 0x961f9820ad417d34ULL;
};

template<class ContainerAllocator>
struct DataType< ::optimizer::NewMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "optimizer/NewMsg";
  }

  static const char* value(const ::optimizer::NewMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::optimizer::NewMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image coloredImage\n"
"geometry_msgs/PoseStamped POSE\n"
"geometry_msgs/Point[] LSDMap \n"
"float32[] depth\n"
"float64 scale\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::optimizer::NewMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::optimizer::NewMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coloredImage);
      stream.next(m.POSE);
      stream.next(m.LSDMap);
      stream.next(m.depth);
      stream.next(m.scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::optimizer::NewMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::optimizer::NewMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coloredImage: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.coloredImage);
    s << indent << "POSE: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.POSE);
    s << indent << "LSDMap[]" << std::endl;
    for (size_t i = 0; i < v.LSDMap.size(); ++i)
    {
      s << indent << "  LSDMap[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.LSDMap[i]);
    }
    s << indent << "depth[]" << std::endl;
    for (size_t i = 0; i < v.depth.size(); ++i)
    {
      s << indent << "  depth[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.depth[i]);
    }
    s << indent << "scale: ";
    Printer<double>::stream(s, indent + "  ", v.scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPTIMIZER_MESSAGE_NEWMSG_H
